### PR TITLE
Adds SerializeMixin

### PR DESCRIPTION
**Pull request by jonatasleon**
This pull request implements SerializeMixin with to_dict() method (following #2)
I created tests and examples.

I took liberty to add a param nest to `to_dict(nested=False)` method, as I wrote in the docstring, it's a:
> flag to return nested relationships' data if true

Note this behavior returns only one depth of nested relationships.

### CODE REVIEW

**Comment by absent1706** [comment]
Thanks for your help, @jonatasleon !
It's really useful!
I will try to release a new PyPi version with this change ASAP

**Comment by jonatasleon** [comment]
Thanks for merge and release so quickly.
I'll try work on the others feature requests.

**Comment by antgel** [comment]
@jonatasleon What would be a typical use case for this? Say, an alternative to `marshmallow-sqlalchemy`?

**Comment by jonatasleon** [comment]
@antgel `marshmallow-sqlalchemy` allow you make rules with more complexity for serialize and deserialize. `SerializeMixin` fit simpler cases, when just the object as `dict` it's enough.

**Pull request merged**
