### PR TITLE
Exception safe crud functions

### PR DESCRIPTION
**Pull request by s-bose**
Hi. I noticed that the mixins don't work well when the database throws an exception on things such as constraint violation. I've created a custom Exception class that handles the sqlalchemy IntegrityError and used it in the crud functions.
I've made save() a separately callable function instead of merging it with the crud functions since that way the ambiguity between autocommit true/false is resolved.

I'd appreciate it if you could go through the changes. :)

### CODE REVIEW

**Comment by michaelbukachi** [comment]
@s-bose Do you mind elaborating 'don't work well when the database throws an exception'? Maybe provide some snippets?

**Comment by s-bose** [comment]
@michaelbukachi CRUD operations such as insert and delete can cause exceptions from database drivers (psychopg2 in my case) which is then rethrown by sqlalchemy as IntegrityError. 
If there is no one to catch this exception it propagates outwards and causes Internal Server Error in my FastAPI application.

For example, if I don't provide with any exception handling in the mixins library, the following happens when I try to insert the same element twice in a table which has a UniqueKeyConstraint for `handle`:

```python
# mixins/activerecord.py

  def save(self):
        """Saves the updated model to the current entity db.
        """
       # try:
        self.session.add(self)
        self.session.flush()
        if not self.session.autocommit:
            self.session.commit()
        # except IntegrityError as e:
        #    self.session.rollback()
        #    raise DBException(name="Insertion Error", cause=str(e))
        return self

# models.py (fastapi route)
@router.post("/") 
def create_models(
    request: Request,
    new_model: ModelsInsert,
    site_id: int
):

   ...

    inserted_model = Models.create(
        site_id=site.id, **new_model.dict()
    ).save()

    return inserted_model.to_dict()
```
This causes the following error in the server log and an Internal Server Error.

```
INFO:     127.0.0.1:52272 - "POST /api/models/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/shiladitya/Desktop/cms-api/app/api/routes/models.py", line 57, in create_models
    inserted_model = Models.create(
  File "/home/shiladitya/Desktop/cms-api/app/db/mixins/activerecord.py", line 31, in save
    self.session.flush()
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/shiladitya/Desktop/cms-api/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "site_handle_unique"
DETAIL:  Key (site_id, handle)=(3, m1) already exists.
```

Now if I uncomment the lines of `save()` in `activerecord.py`, I can add a  exception handler in `main.py`:
```python

# main.py
app = FastAPI()

app.include_router(api_router, prefix = "/api")


@app.exception_handler(DBException)

def db_exception_handler(request: Request, exc: DBException):

    return JSONResponse(
        status_code=400,
        content= {
            "message": "Database error",
            "detail" : str(exc)
        }
    )

```

Then the following happens when I try inserting duplicates:

```
# server log:
INFO:     127.0.0.1:52592 - "POST /api/models/ HTTP/1.1" 400 Bad Request

# response body:
{
  "message": "Database error",
  "detail": "<name: Insertion Error, cause: (psycopg2.errors.UniqueViolation)>"
}
```

This will work for not only UniqueViolation, but also CheckConstraintViolation, NotNullViolation, basically any exception cased by the Database driver.

**Comment by s-bose** [comment]
P.s. I could alternatively try handling the integrityError exception itself from main but it didn't work for me. It still gave me  Internal Server Error. 
Also, the reason I made this PR is that I think this makes the database error abstracted away from the other part of the application using the mixins. It is (probably) driver agnostic so it should also work with mySQL drivers as well. 
I have also made customized DBException messages for different DB actions such as  `insertion error`, `deletion error`, along with the cause section that uses a trimmed out message from the `IntegrityError` 's cause which is shown above.

**Comment by michaelbukachi** [comment]
Hey @s-bose, I think the errors handling thrown by the user should be handled by the user. Introducing another exception class to the library is a major change that we would like to avoid. For your use case, I would advise adding a `try..except` clause around the queries and handling them appropriately.

**Comment by s-bose** [comment]
Alright. Understood. I'm closing the PR then.

**Pull request closed without merging**
