### PR TITLE
Filter operators rebase

### PR DESCRIPTION
**Pull request by fredludlow**
Rebase of #49 on current master.

As previously commented, this is a bit of an experiment. It currently works well for me, but I'm very happy to play around with the syntax if anyone has suggestions for improvement,

### CODE REVIEW

**Comment by fredludlow** [comment]
ps. Travis CI (triggered by pushing to my fork rather than creating the PR) failed for python 3.3 (the typing package not compatible). 

If the intention is still to support python 3.3 (not relevant for me but maybe for others) then I think typing version 3.6.6 would support 3.3 https://pypi.org/project/typing/3.6.6/

**Comment by michaelbukachi** [comment]
> ps. Travis CI (triggered by pushing to my fork rather than creating the PR) failed for python 3.3 (the typing package not compatible).
> 
> If the intention is still to support python 3.3 (not relevant for me but maybe for others) then I think typing version 3.6.6 would support 3.3 https://pypi.org/project/typing/3.6.6/

Python 3.3 reached it's end-of-line 3 years ago (https://endoflife.date/python). So I think we can stop supporting it.

**Comment by PrasanthChettri** [comment]
@michaelbukachi will this be merged in the future ? seems useful

**Comment by michaelbukachi** [comment]
Hi @PrasanthChettri yes, eventually. We are still trying to see if this is the best approach to handle or/and operators.

**Comment by michaelbukachi** [comment]
@fredludlow One more thing. Is this PR a breaking change? Will users be able to still use `filters` the same they have been doing so before?

**Comment by fredludlow** [comment]
My intention was that it wasn't going to break any existing behaviour (I added some new tests for the extended behaviour but the old tests should still all pass)

**Comment by michaelbukachi** [comment]
Awesome. Thanks.

**Comment by michaelbukachi** [comment]
I'll do a release over the weekend.

**Pull request merged**
